FROM alpine:edge

WORKDIR /usr/src/app
COPY navitia/source/jormungandr/requirements.txt /usr/src/app
COPY navitia/source/jormungandr/jormungandr /usr/src/app/jormungandr
COPY navitia/source/navitiacommon/navitiacommon /usr/src/app/navitiacommon

RUN echo http://dl-3.alpinelinux.org/alpine/edge/testing  >> /etc/apk/repositories

RUN apk --update --no-cache add \
        g++ \
        build-base \
        python-dev \
        py2-pip \
        zlib-dev \
        linux-headers \
        musl \
        musl-dev \
        git \
        geos \
        postgresql-dev && \
    pip install -U pip && \
    pip install --no-cache-dir uwsgi && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del \
        g++ \
        build-base \
        python-dev \
        zlib-dev \
        linux-headers \
        musl \
        musl-dev

# ....
# I don't see a better way, geos try to find libc and fail, so ugly hack to give it
RUN ln -s /lib/ld-musl-x86_64.so.1 /usr/lib/libc.so

EXPOSE 5000

WORKDIR /usr/src/app/

RUN echo "SQLALCHEMY_DATABASE_URI = 'postgresql://navitia:navitia@database/jormungandr'" > /jormun_settings.py

ENV JORMUNGANDR_CONFIG_FILE=/jormun_settings.py
ENV PYTHONPATH=.
CMD ["uwsgi", "--mount", "/=jormungandr:app", "--http", "0.0.0.0:80"]
