FROM alpine:edge

WORKDIR /usr/src/app
COPY source/tyr/requirements.txt /usr/src/app
COPY source/tyr/tyr /usr/src/app/tyr
COPY source/navitiacommon/navitiacommon /usr/src/app/navitiacommon

# we need geos and for the moment it's only on edge
RUN echo http://dl-3.alpinelinux.org/alpine/edge/testing  >> /etc/apk/repositories

RUN apk --update --no-cache add \
        git \
        python-dev \
        py2-pip \
        postgresql-dev \
        gcc \
        geos \
        protobuf \
        musl-dev \
        python-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del \
            python-dev \
            git \
            gcc

COPY tyr_settings.py /srv/navitia/settings.py

CMD TYR_CONFIG_FILE=/srv/navitia/settings.py PYTHONPATH=.:../navitiacommon python ./manage_tyr.py runserver -r -t 0.0.0.0 -p 80
