FROM alpine:edge

WORKDIR /usr/src/app
COPY source/tyr/requirements.txt /usr/src/app
COPY source/tyr/tyr /usr/src/app/tyr
COPY source/tyr/manage_tyr.py /usr/src/app/
COPY source/navitiacommon/navitiacommon /usr/src/app/navitiacommon

# we need geos and for the moment it's only on edge
RUN echo http://dl-3.alpinelinux.org/alpine/edge/testing  >> /etc/apk/repositories

RUN apk --update --no-cache add \
        git \
        python-dev \
        build-base \
        linux-headers \
        py2-pip \
        postgresql-dev \
        gcc \
        geos \
        protobuf \
        musl-dev \
        python-dev \
    && pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir uwsgi \
    && apk del \
            python-dev \
            git \
            build-base \
            linux-headers \
            gcc

COPY tyr_settings.py /srv/navitia/settings.py

ENV TYR_CONFIG_FILE=/srv/navitia/settings.py
ENV PYTHONPATH=.:../navitiacommon
CMD uwsgi --mount /=tyr:app  --http 0.0.0.0:80
