FROM navitia/python

WORKDIR /usr/src/app
COPY navitia/source/jormungandr/requirements.txt /usr/src/app
COPY navitia/source/jormungandr/jormungandr /usr/src/app/jormungandr
COPY navitia/source/navitiacommon/navitiacommon /usr/src/app/navitiacommon

RUN apk --update --no-cache add \
        g++ \
        build-base \
        python-dev \
        git \
        geos \
        postgresql-dev \
        libpq && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del \
        g++ \
        build-base \
        python-dev \
        zlib-dev \
        musl \
        musl-dev \
        postgresql-dev

# ....
# I don't see a better way, geos try to find libc and fail, so ugly hack to give it
RUN ln -s /lib/ld-musl-x86_64.so.1 /usr/lib/libc.so

EXPOSE 5000

WORKDIR /usr/src/app/

RUN echo "SQLALCHEMY_DATABASE_URI = 'postgresql://navitia:navitia@database/jormungandr'" > /jormun_settings.py

ENV JORMUNGANDR_CONFIG_FILE=/jormun_settings.py
ENV PYTHONPATH=.
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
CMD ["uwsgi", "--mount", "/=jormungandr:app", "--http", "0.0.0.0:80"]
